version: '3.3'
services:
    web: 
        image: nginx:latest
        container_name: "anki-nginx"
        ports:
            -"8888:1888"
        volumes:    
            - /d/Vue03/anke-back/font:/anki/font
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on: 
            - nestjs   
    nestjs:  
        image: nodejscn/node
        container_name: "anki-nestjs"
        ports:
            -"7000:3000"
        volumes:    
            - /d/Vue03/anke-back:/anki
        depends_on: 
            - mysql   
    mysql: 
        image: mysql
        container_name: "anki-mysql"
        ports:
            -"3306:3306"
        volumes:      
            -  /d/Vue03/anke-back/mysql/conf:/etc/mysql/conf.d
            -  /d/Vue03/anke-back/mysql/data:/var/lib/mysql